export function Texts() {
    return (
        <>
         <h1>Linh and Tam wedding</h1>
        
      <h1>Vite + React</h1>
      <div className="">
       <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut dapibus elementum tortor, eu suscipit purus. Morbi placerat felis varius, egestas magna a, tristique sem. Proin id fringilla velit. Duis sapien erat, iaculis et nulla ut, molestie rutrum magna. Sed ut quam mauris. Ut dapibus ipsum iaculis leo sagittis sagittis. Vestibulum nec quam et tellus condimentum varius a vitae lorem. Mauris volutpat ullamcorper congue. Donec semper eleifend ultricies. Nunc ac cursus quam. Quisque maximus libero quis lobortis egestas. Vivamus consectetur quam non justo pharetra efficitur. Maecenas fringilla turpis turpis, eu efficitur metus finibus quis. Phasellus posuere metus quis mattis porttitor. Maecenas vel nulla et ligula dictum luctus vel quis purus.</p>
      </div>
      <p className="">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam mollis diam in condimentum tincidunt. Curabitur elementum diam efficitur lorem pulvinar fermentum. Etiam eu urna consectetur, finibus metus non, tempus massa. Morbi scelerisque posuere lobortis. Donec accumsan laoreet risus, eget elementum lorem sodales at. Nunc congue elit turpis, at egestas mi accumsan vel. Nulla suscipit neque nisl, in aliquam mauris laoreet vel. Nam ornare facilisis leo sit amet suscipit. Vivamus ullamcorper tempor odio, sollicitudin ullamcorper velit rutrum vel. Ut nec aliquet mi.

Praesent sed velit vel lectus molestie efficitur. Aliquam pulvinar nulla neque. Nulla eu accumsan tellus. Mauris vitae dictum est. Donec ultrices varius neque, non volutpat risus porta a. Donec varius semper aliquet. Nulla egestas porta elementum. Suspendisse et leo tincidunt sapien ultricies blandit id vitae nibh. Maecenas vel magna a leo tempor molestie. Aliquam erat volutpat. Mauris purus dolor, condimentum ut sem sed, laoreet bibendum elit.

Donec vel ex arcu. In non magna ligula. Quisque felis lacus, feugiat eget est ac, tincidunt tincidunt odio. Praesent sem felis, maximus ac scelerisque nec, molestie at diam. Sed vitae porttitor sapien. Etiam posuere, nunc finibus gravida tempor, sem ante ultricies felis, sed ornare nisl erat sed tellus. Integer pharetra lectus eget maximus dignissim. Praesent sem libero, luctus at lectus eu, bibendum dapibus neque. Ut eget purus eu ligula fermentum egestas in consectetur orci. Donec dictum diam elit, quis interdum metus hendrerit et. Nullam in velit efficitur, lobortis eros ut, bibendum velit. Nullam dignissim mauris velit, nec posuere nisi finibus a. Cras non ante ac elit sodales venenatis ac vitae sem. Proin scelerisque nisi a vehicula sodales.

Nunc in augue magna. Quisque commodo arcu tellus, ac hendrerit eros blandit non. Proin vitae lacus justo. Morbi eu volutpat mi. Integer faucibus ex luctus orci consequat, vitae iaculis nisi maximus. Morbi quis quam nec mi laoreet dictum. Curabitur ante eros, placerat sed arcu a, malesuada eleifend nisi. Etiam sed vehicula urna. Ut vel lorem pellentesque, lobortis elit sed, blandit risus. Proin non ex massa.

In nec fermentum erat. Nullam in luctus dui. Nulla vel tempor risus. Sed fermentum accumsan magna vel eleifend. Maecenas volutpat urna orci, ac pellentesque mauris pulvinar id. Nullam tempor turpis erat, vitae molestie odio porta quis. Sed suscipit risus enim, ut pharetra quam semper dictum.

Nulla ut commodo velit. Sed lacinia risus eget tellus convallis, id varius arcu egestas. Aliquam urna nibh, dapibus a arcu ut, interdum suscipit risus. Maecenas mollis diam sit amet diam sodales, vel convallis libero facilisis. Nullam iaculis ipsum nunc, in feugiat dui convallis pretium. Vivamus eu elementum neque, vitae aliquam elit. In consectetur pretium consequat. Sed egestas dui lacus, a lobortis libero mollis nec. Maecenas tincidunt congue risus, facilisis tincidunt ipsum. Quisque finibus tortor vel nisi rhoncus eleifend. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed luctus mi at sem viverra feugiat. Fusce finibus facilisis nibh id tincidunt.

Nunc libero risus, dignissim et scelerisque sed, tincidunt laoreet lectus. Morbi lacinia metus non malesuada cursus. Sed massa odio, bibendum non fringilla auctor, euismod in dolor. Donec a efficitur sem. Cras venenatis, lectus sed blandit laoreet, ex magna mollis risus, id bibendum quam tellus id tellus. Nam et vestibulum sapien. Duis sit amet tortor vitae dolor congue vestibulum. In rutrum magna justo, in pharetra tortor pellentesque et. Proin dapibus nisl et luctus consequat. Vestibulum pulvinar mattis tortor id accumsan. Quisque eget vehicula sapien. Vestibulum vel placerat augue, ac molestie orci.

Donec ornare eros magna, non sollicitudin lorem rutrum quis. Maecenas eu ornare lorem. Nulla arcu urna, dignissim ultrices metus et, sagittis bibendum tortor. Duis quis mauris purus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean rutrum bibendum vulputate. Pellentesque tellus diam, dictum bibendum tortor sed, scelerisque gravida risus. Mauris sollicitudin aliquam ipsum, vitae ultrices nisl mollis porta. Fusce eget imperdiet lacus, sit amet efficitur massa.

Duis quis ante ante. Nulla id diam ut augue fermentum mattis. Mauris ut luctus felis, ac maximus tellus. Donec vitae lorem in ipsum laoreet dapibus in non metus. Donec sit amet tellus a ex mattis scelerisque. Donec congue erat sed lectus pellentesque molestie. Suspendisse luctus quam sit amet tortor blandit commodo id vel urna. Sed blandit eleifend efficitur. Proin non ullamcorper tortor, eget auctor tortor. Mauris vehicula sapien et enim molestie, at imperdiet risus egestas. Nunc venenatis, turpis in vestibulum pretium, mi urna laoreet ex, posuere ultrices nisl nulla sit amet quam. Cras auctor purus eget massa pharetra sagittis. Curabitur dignissim, velit in iaculis aliquam, orci mauris faucibus sapien, eu interdum odio velit quis ligula. Praesent quis pellentesque mauris. Duis tempus urna purus, id faucibus sem rhoncus vitae. Fusce lacinia nisi in ex tincidunt, scelerisque placerat odio fringilla.

Sed ac malesuada urna, id laoreet ex. Donec vel turpis eleifend nisl cursus pulvinar id vel mauris. Cras dapibus convallis arcu, posuere condimentum risus elementum ut. Nulla blandit nisl et ultrices feugiat. Vestibulum vehicula semper interdum. Nunc ut dolor scelerisque, feugiat ante sit amet, accumsan metus. Sed sem nunc, tempor et varius sit amet, dapibus et magna. Nam porttitor et sapien ut tincidunt. Vestibulum non ex libero. Mauris vel enim scelerisque, consequat turpis at, suscipit velit. Proin eget scelerisque ipsum.
      </p>
        </>
    );
}